version: '3.8'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: ./pipeline
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jenkins/jenkins-data/pipeline/java-app:/var/java-app
    group_add:
      - "992"
    networks:
      - net

  remote_host:
    container_name: remote_host
    image: remote_host
    build:
      context: ./fedora
    networks:
      - net
    volumes:
      - ./aws-s3.sh:/tmp/script.sh

  sql_host:
    container_name: sql_host
    image: mysql
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net

  web:
    container_name: web
    image: ansible-web
    build:
      context: ./ansible/web
    ports:
      - "80:80"
    networks:
      - net

networks:
  net:

volumes:
  db_data: